### ISSUE TITLE
Can You help me to configure this widget please

### ISSUE THREAD

**Issue by JMarkyBB** [felixhageloh/weather-widget#40]
I'm having trouble configuring this weather widget, I can't get it to recognise my location, if its not to much trouble Felix

![screen shot 2017-10-11 at 1 19 37 pm](https://user-images.githubusercontent.com/27829143/31440338-799829e6-ae87-11e7-82fc-e39d995f9e05.png)

**Comment by felixhageloh** [comment]
On yahoo weather I can find these two locations (not sure which one matches best for your location). Maybe using 'GB'  instead of 'UK' and either Thornton or Cleveleys will work. 

<img width="331" alt="screen shot 2017-10-15 at 10 54 51" src="https://user-images.githubusercontent.com/367503/31583236-63562800-b197-11e7-951d-a0ab7e9275b9.png">

**Comment by JMarkyBB** [comment]
Cheers Felix, that worked. 

Thanks.


Mark

**Comment by felixhageloh** [comment]
glad I could help!
